### PR TITLE
Fix for configure error caused by 'Could NOT find Sphinx (missing:  S…

### PR DESCRIPTION
**Pull request by ashahba**
…PHINX_VERSION)'

### CODE REVIEW

**Comment by ashahba** [comment]
This fixes #66

**Comment by ashahba** [comment]
@zach-nervana would please direct me to the right reviewer for this PR?

**Comment by zach-nervana** [comment]
Sorry, I'm not sure, @rkimballn1 do you know who should review and merge?

**Comment by sfraczek** [comment]
Hi,
I have answered to your issue #66, please take a look and say what you think.

**Pull request closed without merging**
